first create
privacy-scaling-explorations/pse.dev pull request #163
Opened 2024-04-12 13:50 UTC by zukizukizuki

2024-04-12 14:26 UTC, zukizukizuki commented
@ChialiT 
please check it.

2024-04-17 01:01 UTC, zukizukizuki commented
@ChialiT 
How's it going?

2024-04-17 21:08 UTC, ChialiT commented
> @ChialiT How's it going?

Thank you for pinging me, I asked one of our member to review the translation. my Japanese is very limited.

2024-04-22 09:02 UTC, tkmct commented
Hi @zukizukizuki, thank you for your contribution. I'm currently reviewing your translation. Bear with me for a moment please.

2024-04-22 11:50 UTC, tkmct requested changes
Thank you very much for your contribution. I added suggestions in the PR.
Please take a look and accept those suggestions. If you need any help, let us know.

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +    "faq": "よくある質問 (FAQ)",
```suggestion
    "faq": "よくある質問",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +    "curriculum": "カリキュラム (Curriculum)",
```suggestion
    "curriculum": "カリキュラム",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +    "howToApply": "応募方法 (How to apply)",
```suggestion
    "howToApply": "応募方法",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +    "applyNow": "今すぐ応募する (Apply now)",
```suggestion
    "applyNow": "今すぐ応募する",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +    "learnMoreOnGithub": "GitHubで詳細を見る (Learn more on Github)",
```suggestion
    "learnMoreOnGithub": "GitHubで詳細を見る",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +    "week": "Week {{week}} (週 {{week}})"
```suggestion
    "week": "第{{week}}週"
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +      "title": "前提条件 (PRE-REQUISITES)",
```suggestion
      "title": "必須条件",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +        "コースの概要とリソース (Course overview and resources)",
```suggestion
        "コースの概要とリソース",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +        "Git、GitHub、およびPRワークフローの基本 (Git, GitHub, and PR workflow basics)",
```suggestion
        "Git、GitHub、およびPRワークフローの基本",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +        "ゼロ知識証明 (ZKPs) と数論の入門 (Introduction to ZKPs and Number Theory)"
```suggestion
        "ゼロ知識証明 (ZKPs) と数論の入門"
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +      "title": "暗号の基本 (Cryptographic Basics)",
```suggestion
      "title": "暗号学の基礎",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +        "Circom入門 (Getting started with Circom)",
```suggestion
        "Circom入門",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +        "暗号化とハッシュ関数の基礎 (Basics of encryption and hash functions)",
```suggestion
        "暗号化とハッシュ関数の基礎",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +        "デジタル署名と楕円曲線暗号 (Digital signatures and elliptic curve cryptography)"
```suggestion
        "デジタル署名と楕円曲線暗号"
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +      "title": "より高度な暗号化 + ZKP (More Crypto + ZKPs)",
```suggestion
      "title": "より高度な暗号技術とZKP",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +        "Circom 集中講座 + 実践 (Circom crash course + practice)",
```suggestion
        "Circom 集中講座 + 実践",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +        "KZGコミットメントと zkSNARK (KZG Commitments and zkSNARKs)",
```suggestion
        "KZGコミットメントと zkSNARKs",
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/programs-page.json
> +        "信頼されたセットアップと Groth16 の概要 (Overview of Trusted Setups and Groth16)"
```suggestion
        "トラステッドセットアップと Groth16 の概要"
```

2024-04-22 11:50 UTC, tkmct commented on app/i18n/locales/jp/common.json
> +  "siteDescription": "暗号研究と共同実験を通じてイーサリアムを強化する",
```suggestion
  "siteDescription": "暗号学研究とコレクティブな実験を通じてイーサリアムをよりよくする",
```

2024-04-22 13:33 UTC, zukizukizuki commented
@tkmct 
thank you for your review!
All imported.

2024-04-22 13:46 UTC, tkmct requested changes
I'm sorry, I missed one change. Can you apply the suggested change too?

2024-04-22 13:46 UTC, tkmct commented on app/i18n/locales/jp/about-page.json
> +  "description": "PSEはイーサリアム財団が支援する研究開発ラボで、暗号プリミティブのユースケースを試すことに専念しています。私たちは、オープンソースのインフラやツールの開発、ワークショップやサマープログラムの開催、そして暗号学を現実のものにしようとする人々とのコラボレーションなどを行います。",
```suggestion
  "description": "PSEはイーサリアムファウンデーションが支援する研究開発ラボで、暗号プリミティブのユースケースを試すことに専念しています。私たちは、オープンソースのインフラやツールの開発、ワークショップやサマープログラムの開催、そして暗号学を現実のものにしようとする人々とのコラボレーションなどを行います。",
```

2024-04-22 13:53 UTC, tkmct approved these changes
Thanks! LGTM.

2024-04-22 14:07 UTC, zukizukizuki commented
@tkmct (@ChialiT) 
thank you!Waiting for approval.

2024-06-06 16:18 UTC, AtHeartEngineer commented
@tkmct Do you think this is ready to merge?

2024-06-19 03:02 UTC, ChialiT approved these changes

2024-06-19 12:16 UTC, ChialiT commented
@AtHeartEngineer can u approve this one so i can merge it?thanks

2024-06-19 12:48 UTC, AtHeartEngineer approved these changes

2024-06-20 12:08 UTC, merged